import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const gothamNarrow = localFont({
  src: [
    { path: "./fonts/GothamNarrow-Bold.woff2", weight: "700", style: "normal" },
    { path: "./fonts/GothamNarrow-Black.woff2", weight: "900", style: "normal" },
  ],
  variable: "--font-gotham-narrow",
  display: "swap",
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${openSans.variable} ${gothamNarrow.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
